name: Publish to Heroku

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          cd demo/
          bundle install
          bundle update microsoft_teams_incoming_webhook_ruby
          cd ../
      - name: Define Heroku credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Define Heroku git remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Publish to Heroku
        run: |
          git config user.name 'Pedro Furtado'
          git config user.email 'pedro.felipe.azevedo.furtado@gmail.com'
          git add --all
          git commit -m 'Publish to Heroku'
          git push heroku master --force
